openapi: 3.1.0
info:
  version: 1.0.0
  title: дз 8
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: тут я делаю дз 8
tags:
  - name: Contacts
    description: Операції над контактами
  - name: Auth
    description: Авторизація та реєстрація

servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-qrqo.onrender.com

paths:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
