openapi: 3.1.0
info:
  version: 1.0.0
  title: дз 8
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: тут я делаю дз 8

tags:
  - name: Contacts
    description: Операції над контактами
  - name: Auth
    description: Авторизація та реєстрація

servers:
  - url: https://nodejs-hw-mongodb-qrqo.onrender.com

paths:
  /contacts:
    get:
      tags:
        - Contacts
      summary: Отримати всі контакти
      operationId: getAllContacts
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Успішна відповідь
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '401':
          description: Неавторизовано

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: []
